### ISSUE TITLE
Handle PowerShell update

### ISSUE THREAD

**Issue by rstolpe** [rstolpe/WinSoftwareUpdate#19]
When PowerShell has a new update it will cause the script to crash as it runs on PowerShell it can't update it when it runs.
Fix:
* If PowerShell has a update download it from GitHub
* Close script run PowerShell MSI update silently
* When finish open script again and run it once more.

**Comment by Shift-CTRL0505** [comment]
I got this error when I ran Update-RSWinSoftware:

=== This messages is expected if you are using PowerShell 7 or higher ===

ParentContainsErrorRecordException: Exception calling "GetSteppablePipeline" with "1" argument(s): "The expression after '&' in a pipeline element
produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object."

I know it says that it's expected behaviour, I was just trying to find out when it will be fixed?

Thanks,

Lee

**Comment by rstolpe** [comment]
> I got this error when I ran Update-RSWinSoftware:
> 
> 
> 
> === This messages is expected if you are using PowerShell 7 or higher ===
> 
> 
> 
> ParentContainsErrorRecordException: Exception calling "GetSteppablePipeline" with "1" argument(s): "The expression after '&' in a pipeline element
> 
> produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object."
> 
> 
> 
> I know it says that it's expected behaviour, I was just trying to find out when it will be fixed?
> 
> 
> 
> Thanks,
> 
> 
> 
> Lee

Got it on my to-do, I'm currently at business trip.
But I'm back within two weeks. I can check on it then.

**Comment by rstolpe** [comment]
@Shift-CTRL0505 I'll take a look at this, this week and fix it.
Also add some other things to it, for example will it work with ARM64 and x86 also :)

**Comment by rstolpe** [comment]
@Shift-CTRL0505 update with a new release will be uploaded during this week.
Sorry for the delay.

I have built it so that it will check against PowerShell repo for any new updates and if its updates it will update powershell with the .msi file.
No need to restart powershell.
Then it will continue with winger.

**Comment by rstolpe** [comment]
Closing this one as it's solved in up coming release, planning to release it within two days.
